MouauEasyGo/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'
urlpatterns = [
	# path('', views.RedirectUserView.as_view(), name='redirect'),
    path('post/', views.PostListView.as_view(), name='home'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user-posts'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.About.as_view(), name='blog-about')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    path('contact/', views.Contact.as_view(), name='contact'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from user.models import User
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    time_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk':self.pk})

blog/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from .models import Post
from user.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse

# class RedirectUserView(generic.RedirectView):
# 	url = '/user/'


class PostListView(generic.ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-time_posted']
    paginate_by = 5


class UserPostListView(generic.ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-time_posted')


class PostDetailView(generic.DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class About(generic.TemplateView):
	template_name = 'blog/about.html'
	
	def get_context_data(self, **kwargs):
		context = super(About, self).get_context_data(**kwargs)
		context['title'] = 'about'
		return kwargs

home/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'home/home.html'

class About(TemplateView):
    template_name = 'home/about.html'
    
    
class Contact(TemplateView):
    template_name = 'home/contact.html'

blog/templates/blog/about.html
{% extends "user/base.html" %}

{% block content %}

<div class="jumbutron">
    <div class="">
        <p>About Us</p>
    </div>
</div>

{% endblock %}

blog/templates/blog/home.html
{% extends "user/base.html" %}
{% block content %}

{% for post in posts %}
<div class="media">
  <div class="media-body">
    <div class="container">
      <div class="row">
        <div class="col-lg-1">
          <img class="rounded-circle mr-3 account-img" src="{{ post.author.profile.image.url }}" />
        </div>
        <div class="col-lg-10 ml-3">
          <h1><a href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h1>
          <p class="lead">
            by
            <a href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
          </p>
        </div>
        <p class="small">Posted on {{ post.date_posted|date:"F d, Y" }}</p>
      </div>
    </div>

    <hr />

    <p class="lead mt-0">{{ post.content }}</p>
    <hr />
  </div>
</div>
{% endfor %}

{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-3" href="?page=1">First</a>
<a class="btn btn-outline-info mb-3" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-3" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-3" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-3" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-3" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}
{% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "user/base.html" %} {% block content %}

<div class="jumbutron">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete Post</legend>
    </fieldset>
    <h2>Are you sure you want to delete the post {{ object.title }}</h2>
    <div class="form-group">
      <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
    </div>
  </form>
  <div class="border-top pt-3"></div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "user/base.html" %} {% block content %}
<div class="media">
    <div class="media-body">
        <div class="container">
            <div class="row">
                <div class="col-lg-1">
                    <img class="rounded-circle mr-3 account-img" src="{{ object.author.profile.image.url }}" />
                </div>
                <div class="col-lg-10 ml-3">
                    <h1>{{ object.title }}</h1>
                    <p class="lead">
                        by
                        <a href="{% url 'blog:user-posts' post.author.username %}">{{ object.author }}</a>
                    </p>
                </div>
                <p class="small">Posted on {{ object.date_posted|date:"F d, Y. h:i A" }}</p>
            </div>
            {% if object.author == user %}
            <div>
                <a class="btn btn-outline-secondary btn-sm mt-1 mb-1"
                    href="{% url 'post-update' object.id %}">Update</a>
                <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
            </div>
            {% endif %}
        </div>

        <hr />

        <p class="lead mt-0">{{ object.content }}</p>
        <hr />
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content_section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Post</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Post
            </button>
        </div>
    </form>
</div>

{% endblock %}

blog/templates/blog/user_posts.html
{% extends "user/base.html" %}
{% block content %}

<h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
{% for post in posts %}
<div class="media">
    <div class="media-body">
        <div class="container">
            <div class="row">
                <div class="col-lg-1">
                    <img class="rounded-circle mr-3 account-img" src="{{ post.author.profile.image.url }}" />
                </div>
                <div class="col-lg-10 ml-3">
                    <h1><a href="{% url 'blog:post-detail' pk=post.id %}">{{ post.title }}</a></h1>
                    <p class="lead">
                        by
                        <a href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
                    </p>
                </div>
                <p class="small">Posted on {{ post.time_posted|date:"F d, Y. h:i A" }}</p>
            </div>
        </div>

        <hr />

        <p class="lead mt-0">{{ post.content }}</p>
        <hr />
    </div>
</div>
{% endfor %}

{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-3" href="?page=1">First</a>
<a class="btn btn-outline-info mb-3" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-3" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-3" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-3" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-3" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}
{% endif %}
{% endblock content %}