MouauEasyGo/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'
urlpatterns = [
	# path('', views.RedirectUserView.as_view(), name='redirect'),
    path('post/', views.PostListView.as_view(), name='home'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user-posts'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.About.as_view(), name='blog-about')
]

user/urls.py
from django.urls import path
from user import views as user_views


urlpatterns = [

    path('', user_views.user_profile_detail_view.as_view(),
         name="user_profile_detail"),

    path('profile/<int:pk>/',
         user_views.profile_detail_view.as_view(), name="profile_detail"),

    path('profile/update/', user_views.update_profile.as_view(),
         name="profile_update")
         
]

user/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.shortcuts import reverse


class CustomAccountManager(BaseUserManager):

    def _create_user(self, email, username, firstname, lastname, password, **other_fields):
        """create and saves the user with the given info"""

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, firstname=firstname, lastname=lastname, **other_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, firstname, lastname, password=None, **other_fields):
        other_fields.setdefault('is_superuser', False)
        other_fields.setdefault('is_staff', False)
        other_fields.setdefault('is_active', True)

        return self._create_user(email, username, firstname, lastname, password, **other_fields)

    def create_superuser(self, email, username, firstname, lastname, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self._create_user(email, username, firstname, lastname, password, **other_fields)


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=150, unique=True)
    firstname = models.CharField(max_length=150)
    lastname = models.CharField(max_length=150)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'firstname', 'lastname']

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return f'/user/profile/{self.pk}/'


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics/")
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.user}'s profile"

    def get_absolute_url(self):
        return f'/user/profile/{self.pk}/'

user/forms.py
from django import forms
from user.models import Profile, User
from allauth.account.forms import SignupForm


class UserRegistrationForm(SignupForm):
    email = forms.EmailField(required= True)
    firstname = forms.CharField(required=False)
    lastname = forms.CharField(required=False)
    date_of_birth = forms.DateField(required=True)
    image = forms.ImageField(required=False)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['firstname'].widget.attrs['placeholder'] = 'firstname'
        self.fields['lastname'].widget.attrs['placeholder'] = 'lastname'
        self.fields['date_of_birth'].widget.attrs['placeholder'] = 'Date of Birth'
        self.fields['image'].widget.attrs['placeholder'] = 'Profile pics'


    def save(self, request):
        user = super(UserRegistrationForm, self).save(request)
        user.firstname = self.cleaned_data['firstname']
        user.lastname = self.cleaned_data['lastname']
        user.profile.date_of_birth = self.cleaned_data['date_of_birth']
        if 'image' in self.cleaned_data:
            user.profile.image = self.cleaned_data['image']
        user.save()
        return user
        

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'image', ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'firstname', 'lastname', ]

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from user.models import Profile, User
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.base import View
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from user.forms import UserRegistrationForm, ProfileUpdateForm, UserUpdateForm
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from user.mixins import Update_view
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie
from braces.views import CsrfExemptMixin
from django.views.generic.base import RedirectView


# class basehome(RedirectView):
#     pattern_name = 'register'



class update_profile(LoginRequiredMixin, Update_view):
    """inheriting the main deadly mixin I wrote"""
    success_url = reverse_lazy('user_profile_detail')
    template_name = "user/profile_update.html"


class profile_detail_view(DetailView):
    template_name = "user/profile_detail.html"
    model = Profile


class user_profile_detail_view(LoginRequiredMixin, DetailView):
    template_name = "user/profile_detail.html"
    model = Profile

    def get_object(self, queryset=None):
        pk = self.request.user.id
        user = User.objects.get(pk=pk)
        queryset = Profile.objects.filter(user=user)
        if queryset:
            # Get the single item from the filtered queryset
            obj = queryset.first()
        else:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj

user/templates/user/Login.html
{% extends "user/base.html" %}

{% load crispy_forms_tags %}
{% load socialaccount %}
{% providers_media_js %}


{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="login" id="login">
    <input type="hidden" name="next" value="{{ next }}">
</form>
<button class="mt-4"><a href="{% provider_login_url 'google' %}">Google Login</a></button>
<button class="mt-4"><a href="{% provider_login_url 'facebook' method='oauth2' %}">Facebook login</a></button>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MouauEasyGo</title>
    <link rel="stylesheet" href="{% static 'user/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/custom_styles.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom_styles.css' %}">

</head>

<body>
    <nav class="nav">
        <a class="nav-link" href="{% url 'blog:home' %}">Blog</a>
        <a class="nav-link" href="#">Inbox</a>
        <a class="nav-link" href="{% url 'user_profile_detail' %}">{{ user }}</a>

        {% if user.is_authenticated %}
        <a class="nav-link" href="#">New message</a>
        <a class="nav-link" href="{% url 'user_profile_detail' %}">profile</a>
        <a class="nav-link" href="{% url 'account_logout' %}">logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'account_login' %}">login</a>
        <a class="nav-link" href="{% url 'account_signup' %}">register</a>

        {% endif %}
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-7 pt-4">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

user/templates/user/logout.html
{% extends "user/base.html" %}
{% block content %}

<p>You are successfully logged out.</p>


<p class="card pt-3"><a href="{% url 'account_login' %}">Log in Again</a></p>

{% endblock %}

user/templates/user/password_change_done.html
{% extends "user/base.html" %}
{% block content %}

<p>Your password has been changed.</p>


<p class="card pt-3"><a href="{% url 'account_login' %}">Log in</a></p>

{% endblock %}

user/templates/user/password_change_form.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

{% if form.errors %}
<p>Enter a valid email address and try again.</p>
{% endif %}

<form method="post" action="{% url 'password-change' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update">
</form>
{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

user/templates/user/password_reset.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Reset password">
</form>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends "user/base.html" %}
{% block content %}

<p>Password reset has been completed.</p>


<p class="card pt-3"><a href="{% url 'account_login' %}">Log</a></p>

{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" action="{% url 'password_reset_confirm' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Reset">
</form>

{% endblock %}

user/templates/user/password_reset_done.html
{% extends "user/base.html" %}
{% block content %}

<p>Your reset password has been sent</p>

{% endblock %}

user/templates/user/profile_detail.html
{% extends "user/base.html" %}
{% block content %}


<div class="card">
    <div class="card-header">
        <div class="col-4">
            <img class="img-fluid img-circle account_img" src='{{ user.profile.image.url }}' alt="profile picture">
        </div>
        <div class="col-8">
            <h3>{{ user.firstname }} {{ user.lastname }}</h3>
            <P>{{ user.email }}</P>
        </div>
    </div>
    <div class="card-body">
        <section class="">
            <p class="">{{ user.profile.date_of_birth }}</p>
        </section>
        <a href="{% url 'profile_update' %}" class="btn btn-info">Update</a>

    </div>
</div>

{% endblock %}

user/templates/user/profile_update.html
{% extends 'user/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class='row'>
    <div class="col-12">
        <h1>Form is printed</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ uForm|crispy }}
            {{ pForm|crispy }}
            <button class="btn btn-outline-info" type='submit'>Update info</button>
        </form>
    </div>
</div>

{% endblock content %}

user/templates/user/register.html
{% extends "user/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button id="register" class="btn btn-outline-info" type="submit">Register</button>
</form>


<p class="text-muted underline p-4"><a href="{% url 'login' %}">Have an account? Log in</a></p>

{% endblock %}